[colors.primary]
foreground = "#d4be98"
background = "#1d2021"

[colors.normal]
black = "#665c54"
red = "#ea6962"
green = "#a9b665"
yellow = "#e78a4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#928374"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
