########################################
### BIERSTADT THEME HYPRPAPER CONFIG ###
########################################

# wallpaper {
#   monitor = DP-6
#   path = ~/.dotfiles/themes/wallpapers/Albert_Bierstadt_-_A_Storm_in_the_Rocky_Mountains_Mt._Rosalie.jpg
# }

# wallpaper {
#    monitor = DP-7
#    path = ~/.dotfiles/themes/wallpapers/Albert_Bierstadt_-_Yellowstone_Falls.jpg
# }

splash = false

